baseurl = "https://yura7gi14.github.io/my-portfolio/"
title        = "yuragi.dev"
languageCode = "ja"
defaultContentLanguage = "ja"
theme        = "hello-friend-ng"

[pagination]
  pagerSize = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  hideFooter = true
  enableThemeToggle = true

  # Subtitle for home
  homeSubtitle = "ネットワークが好きな大学院生の活動記録."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "ネットワークが好きな大学院生の活動記録"
  keywords = "ポートフォリオ, ブログ, 技術, 開発"
  images = [""]

  [params.footer]
  trademark  = 2019              # 「© 2019」が自動で出る
  rss        = true              # RSS アイコン
  author     = true              # 上の author.name へのリンク
  copyright  = false             # RSS の左に © 表記を並べたい時は true
  topText    = []                # 今回は未使用
  bottomText = [
    "Powered by <a href=\"https://gohugo.io\">Hugo</a>",
    "Made with &#10084; by <a href=\"https://github.com/rhazdon\">rhazdon</a>",
  ]

  [params.favicon]
  src = "https://yura7gi14.github.io/my-portfolio/favicon-32x32.png"
  type = "image/png"
  sizes = "32x32"



[taxonomies]
    category = "categories"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.ja]
  title = "yuragi.dev"
  keywords = "ブログ, 技術, 開発"
  copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  [languages.ja.params]
    subtitle  = "ネットワークが好きな大学院生の活動記録"

    [languages.ja.params.logo]
      logoText = "yuragi.dev"
      logoHomeLink = "/my-portfolio/"

  [[languages.ja.menu.main]]
  identifier = "1profile"
  name       = "Profile"
  url        = "/profile/"
  weight     = 1

  [[languages.ja.menu.main]]
  identifier = "2blog"
  name       = "Blog"
  url        = "/blog/"
  weight     = 2

  [[languages.ja.menu.main]]
  identifier = "3makes"
  name       = "Projects"
  url        = "/works/"
  weight     = 3

  [[languages.ja.menu.main]]
  identifier = "4contact"
  name       = "Contact"
  url        = "/contact/"
  weight     = 4


  # And you can even create generic menu
